#!/usr/bin/env python3
"""
run-config command
==================

Execute the ClusterCatcher Snakemake pipeline using a configuration file
generated by the create-config command.
"""

import click
import os
import sys
import yaml
import subprocess
from pathlib import Path


def find_snakefile():
    """
    Find the Snakefile location within the installed package.
    
    Returns
    -------
    str
        Path to Snakefile
    """
    # Check relative to this file (development mode)
    cli_dir = Path(__file__).parent
    dev_snakefile = cli_dir.parent / 'snakemake_wrapper' / 'Snakefile'
    if dev_snakefile.exists():
        return str(dev_snakefile)
        
    # Check in installed package location
    import ClusterCatcher
    pkg_dir = Path(ClusterCatcher.__file__).parent
    installed_snakefile = pkg_dir / 'snakemake_wrapper' / 'Snakefile'
    if installed_snakefile.exists():
        return str(installed_snakefile)
        
    # Try site-packages
    import site
    for sp in site.getsitepackages():
        sp_snakefile = Path(sp) / 'snakemake_wrapper' / 'Snakefile'
        if sp_snakefile.exists():
            return str(sp_snakefile)
            
    return None


def validate_config_file(config_path):
    """
    Load and validate configuration file.
    
    Parameters
    ----------
    config_path : str
        Path to configuration YAML
        
    Returns
    -------
    tuple
        (config_dict, errors)
    """
    errors = []
    
    try:
        with open(config_path, 'r') as f:
            config = yaml.safe_load(f)
    except Exception as e:
        return None, [f"Failed to load config: {e}"]
        
    # Basic validation
    required_keys = ['samples', 'output_dir', 'reference']
    for key in required_keys:
        if key not in config:
            errors.append(f"Missing required key: {key}")
            
    return config, errors


@click.command('run-config')
@click.argument('config_yaml', type=click.Path(exists=True))
@click.option(
    '--cores', '-c',
    default=1,
    type=int,
    help='Total number of cores for Snakemake (default: 1)'
)
@click.option(
    '--jobs', '-j',
    default=1,
    type=int,
    help='Number of concurrent jobs (default: 1)'
)
@click.option(
    '--dryrun', '-n',
    is_flag=True,
    default=False,
    help='Perform a dry run (show what would be done)'
)
@click.option(
    '--unlock',
    is_flag=True,
    default=False,
    help='Unlock working directory (if previous run was interrupted)'
)
@click.option(
    '--rerun-incomplete',
    is_flag=True,
    default=False,
    help='Rerun incomplete jobs'
)
@click.option(
    '--keep-going', '-k',
    is_flag=True,
    default=False,
    help='Keep going with independent jobs after error'
)
@click.option(
    '--use-conda',
    is_flag=True,
    default=True,
    help='Use conda environments for rules (default: True)'
)
@click.option(
    '--conda-frontend',
    default='mamba',
    type=click.Choice(['mamba', 'conda']),
    help='Conda frontend to use (default: mamba)'
)
@click.option(
    '--profile',
    type=click.Path(),
    help='Path to Snakemake profile for cluster execution'
)
@click.option(
    '--cluster',
    type=str,
    help='Cluster submission command (e.g., "sbatch --partition=normal")'
)
@click.option(
    '--cluster-config',
    type=click.Path(),
    help='Path to cluster configuration file'
)
@click.option(
    '--latency-wait',
    default=60,
    type=int,
    help='Wait time for filesystem latency in seconds (default: 60)'
)
@click.option(
    '--targets',
    type=str,
    help='Comma-separated list of specific targets to build'
)
@click.option(
    '--until',
    type=str,
    help='Run pipeline until specified rule'
)
@click.option(
    '--forcerun',
    type=str,
    help='Force rerun of specific rules (comma-separated)'
)
@click.option(
    '--verbose', '-v',
    is_flag=True,
    default=False,
    help='Verbose Snakemake output'
)
@click.option(
    '--quiet', '-q',
    is_flag=True,
    default=False,
    help='Quiet Snakemake output'
)
def run_config(config_yaml, cores, jobs, dryrun, unlock, rerun_incomplete,
               keep_going, use_conda, conda_frontend, profile, cluster,
               cluster_config, latency_wait, targets, until, forcerun,
               verbose, quiet):
    """
    Run the ClusterCatcher pipeline from a config file.
    
    This command executes the full Snakemake pipeline using the configuration
    generated by create-config. It supports local execution, cluster submission,
    and various Snakemake options for debugging and optimization.
    
    \b
    Local execution:
      ClusterCatcher run-config config.yaml --cores 16
    
    \b
    Cluster execution (SLURM example):
      ClusterCatcher run-config config.yaml \\
        --cores 100 \\
        --jobs 10 \\
        --cluster "sbatch --partition=normal --nodes=1 --ntasks-per-node {threads} --time 04:00:00"
    
    \b
    Using a Snakemake profile:
      ClusterCatcher run-config config.yaml --profile /path/to/profile
    
    \b
    Dry run to check pipeline:
      ClusterCatcher run-config config.yaml --dryrun
    """
    
    click.echo(f"\n{'='*60}")
    click.echo("ClusterCatcher: run-config")
    click.echo(f"{'='*60}\n")
    
    # Find Snakefile
    snakefile = find_snakefile()
    if snakefile is None:
        click.echo("ERROR: Could not find Snakefile", err=True)
        click.echo("Please ensure ClusterCatcher is properly installed", err=True)
        sys.exit(1)
        
    click.echo(f"Snakefile: {snakefile}")
    
    # Validate config
    click.echo(f"Config: {config_yaml}")
    config, errors = validate_config_file(config_yaml)
    if errors:
        click.echo("ERROR: Configuration validation failed:", err=True)
        for e in errors:
            click.echo(f"  - {e}", err=True)
        sys.exit(1)
        
    click.echo(f"Samples: {len(config.get('samples', {}))}")
    click.echo(f"Output directory: {config.get('output_dir', 'N/A')}")
    
    # Build Snakemake command
    cmd = ['snakemake']
    
    # Core options
    cmd.extend(['--snakefile', snakefile])
    cmd.extend(['--configfile', config_yaml])
    cmd.extend(['--cores', str(cores)])
    cmd.extend(['--jobs', str(jobs)])
    cmd.extend(['--latency-wait', str(latency_wait)])
    
    # Conda options
    if use_conda:
        cmd.append('--use-conda')
        cmd.extend(['--conda-frontend', conda_frontend])
        
    # Execution modifiers
    if dryrun:
        cmd.append('--dryrun')
    if unlock:
        cmd.append('--unlock')
    if rerun_incomplete:
        cmd.append('--rerun-incomplete')
    if keep_going:
        cmd.append('--keep-going')
        
    # Cluster options
    if profile:
        cmd.extend(['--profile', profile])
    if cluster:
        cmd.extend(['--cluster', cluster])
    if cluster_config:
        cmd.extend(['--cluster-config', cluster_config])
        
    # Target options
    if targets:
        cmd.extend(targets.split(','))
    if until:
        cmd.extend(['--until', until])
    if forcerun:
        for rule in forcerun.split(','):
            cmd.extend(['--forcerun', rule])
            
    # Verbosity
    if verbose:
        cmd.append('--verbose')
    if quiet:
        cmd.append('--quiet')
        
    # Print command
    click.echo(f"\n{'='*60}")
    click.echo("Snakemake command:")
    click.echo(f"{'='*60}")
    click.echo(' '.join(cmd))
    click.echo("")
    
    if dryrun:
        click.echo("DRY RUN - showing what would be executed\n")
    else:
        click.echo("Starting pipeline execution...\n")
        
    # Execute Snakemake
    try:
        result = subprocess.run(cmd, check=False)
        
        if result.returncode == 0:
            click.echo(f"\n{'='*60}")
            click.echo("Pipeline completed successfully!")
            click.echo(f"{'='*60}")
            click.echo(f"\nResults in: {config.get('output_dir', 'results')}")
        else:
            click.echo(f"\n{'='*60}")
            click.echo(f"Pipeline failed with exit code: {result.returncode}")
            click.echo(f"{'='*60}")
            sys.exit(result.returncode)
            
    except FileNotFoundError:
        click.echo("ERROR: Snakemake not found in PATH", err=True)
        click.echo("Please ensure Snakemake is installed and activated", err=True)
        sys.exit(1)
    except KeyboardInterrupt:
        click.echo("\n\nPipeline interrupted by user")
        click.echo("To resume, run the same command again")
        click.echo("To unlock if needed: ClusterCatcher run-config config.yaml --unlock")
        sys.exit(130)


if __name__ == '__main__':
    run_config()
